aws_conn_id: aws_conn_id

s3:
  bucket: data-warehouse-bobby
  folder: ExamPreparationETL
  output_df: ExamPreparationETL/output_df
  output_folder: ExamPreparationETL/output_folder
  analytics: ExamPreparationETL/Analytics

snowflake:
  conn_id: my_snowflake_conn
  account: UDNDVED-ZC91948
  warehouse: COMPUTE_WH
  database: SALES_DB
  schema: PUBLIC
  table: sales_summary