CREATE OR REPLACE ROLE RETAIL_ROLE;

USE ROLE RETAIL_ROLE;

CREATE OR REPLACE WAREHOUSE RETAIL_WH
WITH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

USE WAREHOUSE RETAIL_WH;

CREATE OR REPLACE DATABASE RETAIL_DB;

USE DATABASE RETAIL_DB;

CREATE OR REPLACE SCHEMA RAW_LAYER;
CREATE OR REPLACE SCHEMA STAGING_LAYER;
CREATE OR REPLACE SCHEMA CLEANSED_LAYER;
CREATE OR REPLACE SCHEMA BUSINESS_LAYER;
CREATE OR REPLACE SCHEMA PRESENTATION_LAYER;

CREATE OR REPLACE FILE FORMAT STAGING_LAYER.CSV_FORMAT
TYPE = CSV
FIELD_DELIMITER = ','
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"';

CREATE OR REPLACE STAGE STAGING_LAYER.RETAIL_STAGE
URL='s3://data-warehouse-bobby/RegularExamETL/output_folder/'
CREDENTIALS=(

        -- ADD YOUR_ACCESS_KEY AND YOUR_SECRET_KEY BELOW ---

    AWS_KEY_ID='YOUR_ACCESS_KEY'
    AWS_SECRET_KEY='YOUR_SECRET_KEY'
)
FILE_FORMAT = STAGING_LAYER.CSV_FORMAT;

CREATE OR REPLACE TABLE CLEANSED_LAYER.SALES_CLEAN
(
    SALES_ID INT,
    PRODUCT_ID INT,
    REGION STRING,
    QUANTITY INT,
    PRICE NUMBER(10,2),
    TIMESTAMP TIMESTAMP_NTZ,
    DISCOUNT NUMBER(5,2),
    ORDER_STATUS STRING,
    TOTAL_SALES NUMBER(10,2),
    CATEGORY STRING,
    BRAND STRING,
    RATING FLOAT,
    IN_STOCK BOOLEAN,
    LAUNCH_DATE DATE,
    MONTH STRING,
    QUARTER STRING,
    WEEK INT,
    WEEKDAY STRING,
    SALES_BUCKET STRING
);

-- !!! Airflow automatic table loading after startup after the structure has been built up to this point !!! --

COPY INTO CLEANSED_LAYER.SALES_CLEAN
FROM @STAGING_LAYER.RETAIL_STAGE
FILE_FORMAT = (FORMAT_NAME = STAGING_LAYER.CSV_FORMAT)
FILES = ('enrich.csv');

CREATE OR REPLACE TABLE BUSINESS_LAYER.DIM_PRODUCT AS
SELECT DISTINCT
    PRODUCT_ID,
    BRAND,
    CATEGORY,
    RATING,
    IN_STOCK,
    LAUNCH_DATE
FROM CLEANSED_LAYER.SALES_CLEAN;

CREATE OR REPLACE TABLE BUSINESS_LAYER.DIM_DATE AS
SELECT DISTINCT
    TIMESTAMP AS SALES_DATE,
    MONTH,
    QUARTER,
    WEEK,
    WEEKDAY
FROM CLEANSED_LAYER.SALES_CLEAN;

CREATE OR REPLACE TABLE BUSINESS_LAYER.FACT_SALES AS
SELECT
    SALES_ID,
    PRODUCT_ID,
    TIMESTAMP,
    REGION,
    QUANTITY,
    PRICE,
    DISCOUNT,
    TOTAL_SALES,
    ORDER_STATUS
FROM CLEANSED_LAYER.SALES_CLEAN;

CREATE OR REPLACE MATERIALIZED VIEW PRESENTATION_LAYER.MV_SALES_BY_REGION_MONTH AS
SELECT
    REGION,
    MONTH,
    SUM(TOTAL_SALES) AS TOTAL_REVENUE
FROM CLEANSED_LAYER.SALES_CLEAN
GROUP BY
    REGION,
    MONTH;

CREATE OR REPLACE MATERIALIZED VIEW PRESENTATION_LAYER.MV_TOP_PRODUCTS_BY_REVENUE AS
SELECT
    PRODUCT_ID,
    BRAND,
    CATEGORY,
    SUM(TOTAL_SALES) AS TOTAL_REVENUE
FROM CLEANSED_LAYER.SALES_CLEAN
GROUP BY
    PRODUCT_ID,
    BRAND,
    CATEGORY;

CREATE OR REPLACE MATERIALIZED VIEW PRESENTATION_LAYER.MV_REVENUE_TREND AS
SELECT
    TIMESTAMP,
    SUM(TOTAL_SALES) AS TOTAL_REVENUE
FROM CLEANSED_LAYER.SALES_CLEAN
GROUP BY
    TIMESTAMP;

CREATE OR REPLACE MATERIALIZED VIEW PRESENTATION_LAYER.MV_CATEGORY_PERFORMANCE AS
SELECT
    CATEGORY,
    COUNT(*) AS TOTAL_ORDERS,
    SUM(TOTAL_SALES) AS TOTAL_REVENUE,
    AVG(TOTAL_SALES) AS AVERAGE_SALE
FROM CLEANSED_LAYER.SALES_CLEAN
GROUP BY
    CATEGORY;