AWS_KEY = "AKIARGUTYR42PD7ZZ4NM"
AWS_SECRET_KEY = "XXXXXX"
AWS_DEFAULT_REGION = "eu-north-1"

POSTGRESQL_USER = "postgres"
POSTGRESQL_PASSWORD = "2546"
POSTGRESQL_HOST = "localhost"
POSTGRESQL_PORT = 5432
POSTGRESQL_DATABASE = "sales_data"